package cli

import (
	"context"
	"fmt"
	"io"
	"strings"

	"github.com/wangjohn/agent-archive/internal/reader"
	"github.com/wangjohn/agent-archive/internal/storage"
)

// Archive IDs generated by this program are 32 lowercase hex characters.
// Require at least the eight characters list displays so ordinary names do
// not turn into an expensive archive-wide lookup.
func isShortArchiveID(query string) bool {
	if len(query) < minShortSessionID || len(query) >= 32 {
		return false
	}
	for _, ch := range query {
		if (ch < '0' || ch > '9') && (ch < 'a' || ch > 'f') && (ch < 'A' || ch > 'F') {
			return false
		}
	}
	return true
}

func resolveShortArchiveID(ctx context.Context, store storage.ObjectStore, env Env, stderr io.Writer, harness, query string) (string, string, error) {
	sessions, err := reader.ListMetadataWithOptions(ctx, store, archiveSessionsPrefix, reader.Filter{Harness: harness}, reader.ListOptions{
		Cache: listCache(env, false), Skipped: warnSkippedSidecar(stderr, "show"),
	})
	if err != nil {
		return "", "", err
	}
	var sessionID, sessionHarness string
	matches := 0
	for _, session := range sessions {
		if strings.EqualFold(session.SessionID, query) || strings.HasPrefix(strings.ToLower(session.SessionID), strings.ToLower(query)) {
			sessionID, sessionHarness = session.SessionID, session.Harness.Name
			matches++
		}
	}
	switch matches {
	case 0:
		return "", "", fmt.Errorf("no archived session %q (see `agent-archive list`)", query)
	case 1:
		return sessionID, sessionHarness, nil
	default:
		return "", "", fmt.Errorf("short session ID %q matches %d sessions; use a longer ID or --harness", query, matches)
	}
}
